#use image which contains apache with php
FROM php:7.4.13-apache

# create app directory
WORKDIR /var/www
COPY . /var/www

#EXPOSE 9000

#install wget
RUN apt-get update
RUN apt-get install wget -y

#install composer command
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php --install-dir=/bin --filename=composer

#install symfony cli command
RUN wget https://get.symfony.com/cli/installer -O - | bash